### ISSUE TITLE
Jetbrains_Zookeeper's Error

### ISSUE THREAD

**Issue by troders34** [sbjamb/Jetbrains_Zookeeper#1]
First of all, I appreciate your code about this Zookeeper's project.
I've copied your code just now, but it comes error.
Then I tried modify the code.
Still error.
I'm stuck on it.

**Comment by jidnyaasu** [comment]
Can you please specify the error? I.e. what type of error and at what line are you getting the error?
I am still very new to python language and programming overall. I'm still learning. But I will try to resolve the error if possible.
